export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOADING_IN_PROGRESS = 'LOADING_IN_PROGRESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const USER_PROFILE ='USER_PROFILE'
export const PROFILE_FAILED = 'PROFILE_FAILED'

export const SAVE_SUCCESS = 'SAVE_SUCCESS'
export const SAVE_FAILED = 'SAVE_FAILED'

export const LOGOUT_ACTION = 'LOGOUT_ACTION'