export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOADING_IN_PROGRESS = 'LOADING_IN_PROGRESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const USER_PROFILE ='USER_PROFILE'
export const PROFILE_FAILED = 'PROFILE_FAILED'